#!/bin/bash
# QUICK START GUIDE - Run these commands in order

echo "========================================="
echo "HUDUGLUE - QUICK START"
echo "Version 1.0.0"
echo "========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}STEP 1: Generate Secrets${NC}"
echo "Run these commands and save the output:"
echo ""
echo "SECRET_KEY:"
python3 -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
echo ""
echo "APP_MASTER_KEY:"
python3 -c "import os, base64; print(base64.b64encode(os.urandom(32)).decode())"
echo ""
echo "API_KEY_SECRET:"
python3 -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
echo ""
echo -e "${GREEN}✓ Copy these values!${NC}"
echo ""

echo -e "${YELLOW}STEP 2: Configure Environment${NC}"
echo "cp .env.example .env"
echo "nano .env  # Paste secrets above, set DB_PASSWORD, ALLOWED_HOSTS"
echo ""
echo -e "${GREEN}Press ENTER when .env is configured...${NC}"
read

echo -e "${YELLOW}STEP 3: Run Bootstrap Script${NC}"
echo "./scripts/bootstrap_ubuntu.sh"
echo ""
echo -e "${GREEN}This will:${NC}"
echo "  - Install system packages"
echo "  - Create database and user"
echo "  - Set up Python virtual environment"
echo "  - Install dependencies"
echo "  - Run migrations"
echo "  - Collect static files"
echo "  - Optionally create superuser and seed demo data"
echo ""
echo -e "${GREEN}Press ENTER to continue...${NC}"
read

echo -e "${YELLOW}STEP 4: Create Service User${NC}"
echo "sudo useradd -r -s /bin/bash -d /opt/itdocs itdocs"
echo "sudo chown -R itdocs:itdocs /opt/itdocs"
echo "sudo chown -R itdocs:itdocs /var/lib/itdocs"
echo "sudo chown -R itdocs:itdocs /var/log/itdocs"
echo ""

echo -e "${YELLOW}STEP 5: Install Gunicorn Service${NC}"
echo "sudo cp deploy/itdocs-gunicorn.service /etc/systemd/system/"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable itdocs-gunicorn"
echo "sudo systemctl start itdocs-gunicorn"
echo "sudo systemctl status itdocs-gunicorn"
echo ""

echo -e "${YELLOW}STEP 6: Install PSA Sync Timer (Optional)${NC}"
echo "sudo cp deploy/itdocs-psa-sync.service /etc/systemd/system/"
echo "sudo cp deploy/itdocs-psa-sync.timer /etc/systemd/system/"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable itdocs-psa-sync.timer"
echo "sudo systemctl start itdocs-psa-sync.timer"
echo ""

echo -e "${YELLOW}STEP 7: Configure Nginx${NC}"
echo "sudo cp deploy/nginx-itdocs.conf /etc/nginx/sites-available/itdocs"
echo "sudo nano /etc/nginx/sites-available/itdocs  # Update server_name"
echo "sudo ln -s /etc/nginx/sites-available/itdocs /etc/nginx/sites-enabled/"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"
echo ""

echo -e "${YELLOW}STEP 8: Configure Firewall${NC}"
echo "sudo ufw default deny incoming"
echo "sudo ufw default allow outgoing"
echo "sudo ufw allow ssh"
echo "sudo ufw allow http"
echo "sudo ufw allow https"
echo "sudo ufw enable"
echo ""

echo -e "${YELLOW}STEP 9: Install SSL Certificate${NC}"
echo "sudo apt-get install certbot python3-certbot-nginx"
echo "sudo certbot --nginx -d yourdomain.com"
echo ""

echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}DEPLOYMENT COMPLETE!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "Access your platform at: https://yourdomain.com"
echo ""
echo "Default credentials (if demo data was seeded):"
echo "  Username: admin"
echo "  Password: admin"
echo "  (Set up 2FA on first login)"
echo ""
echo "Next steps:"
echo "  1. Login and set up 2FA"
echo "  2. Create production organization"
echo "  3. Add users and assign roles"
echo "  4. Configure PSA integration"
echo "  5. Create assets, passwords, documents"
echo ""
echo "Documentation:"
echo "  - README.md for comprehensive docs"
echo "  - DEPLOYMENT.md for detailed checklist"
echo "  - In-app Documentation page (menu)"
echo "  - In-app About page (user menu)"
echo ""
echo "Logs:"
echo "  sudo journalctl -u itdocs-gunicorn -f"
echo "  sudo tail -f /var/log/itdocs/django.log"
echo "  sudo tail -f /var/log/nginx/itdocs-access.log"
echo ""
echo -e "${GREEN}🎉 Enjoy your new IT Documentation Platform! 🎉${NC}"
