# Generated by Django 6.0.1 on 2026-01-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('documented_by', 'Documented By'), ('credentials', 'Credentials'), ('applies_to', 'Applies To'), ('related_to', 'Related To'), ('responsible_for', 'Responsible For'), ('depends_on', 'Depends On'), ('contains', 'Contains'), ('used_by', 'Used By')], default='related_to', max_length=50)),
                ('source_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='core.organization')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'relations',
                'indexes': [models.Index(fields=['organization', 'source_content_type', 'source_object_id'], name='relations_organiz_c1f810_idx'), models.Index(fields=['organization', 'target_content_type', 'target_object_id'], name='relations_organiz_f7a89b_idx'), models.Index(fields=['relation_type'], name='relations_relatio_f83807_idx')],
            },
        ),
    ]
