# Generated by Django 6.0.1 on 2026-01-09 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='favorites_user_id_6849dd_idx'), models.Index(fields=['user', '-created_at'], name='favorites_user_id_f73cef_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='SecureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('encrypted_content', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-delete after this time', null=True)),
                ('read_once', models.BooleanField(default=False, help_text='Delete after first read')),
                ('require_password', models.BooleanField(default=False, help_text='Require password to decrypt')),
                ('access_password', models.CharField(blank=True, help_text='Hashed password for access', max_length=255)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_notes', to='core.organization')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_secure_notes', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='received_secure_notes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_secure_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secure_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='secure_note_sender__70279a_idx'), models.Index(fields=['-created_at'], name='secure_note_created_c19b68_idx')],
            },
        ),
    ]
