# Generated by Django 6.0.1 on 2026-01-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('website_monitoring', 'Website Monitoring Checks'), ('psa_sync', 'PSA Synchronization'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('domain_expiry_check', 'Domain Expiry Check')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this scheduled task')),
                ('interval_minutes', models.PositiveIntegerField(default=5, help_text='How often to run this task (in minutes)')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last successful execution time', null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='Next scheduled execution time', null=True)),
                ('last_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if failed')),
                ('run_count', models.PositiveIntegerField(default=0, help_text='Total number of executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_tasks',
                'ordering': ['task_type'],
            },
        ),
    ]
