# Generated by Django 6.0.1 on 2026-01-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='azure_ad_auto_create_users',
            field=models.BooleanField(default=True, help_text='Automatically create users on first Azure AD login'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='azure_ad_client_id',
            field=models.CharField(blank=True, help_text='Application (client) ID from Azure portal', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='azure_ad_client_secret',
            field=models.CharField(blank=True, help_text='Client secret (encrypted)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='azure_ad_enabled',
            field=models.BooleanField(default=False, help_text='Enable Azure AD / Microsoft Entra ID authentication'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='azure_ad_redirect_uri',
            field=models.CharField(blank=True, help_text='Redirect URI configured in Azure (e.g., https://yourapp.com/auth/callback)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='azure_ad_sync_groups',
            field=models.BooleanField(default=False, help_text='Sync Azure AD groups to roles'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='azure_ad_tenant_id',
            field=models.CharField(blank=True, help_text='Azure AD Tenant ID (GUID)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_bind_dn',
            field=models.CharField(blank=True, help_text='Bind DN for LDAP queries (e.g., CN=ServiceAccount,OU=Users,DC=example,DC=com)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_bind_password',
            field=models.CharField(blank=True, help_text='Password for bind DN (encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_enabled',
            field=models.BooleanField(default=False, help_text='Enable LDAP/Active Directory authentication'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_group_search_base',
            field=models.CharField(blank=True, help_text='Base DN for group searches (optional)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_require_group',
            field=models.CharField(blank=True, help_text='Require membership in this group (DN, optional)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_server_uri',
            field=models.CharField(blank=True, help_text='LDAP server URI (e.g., ldap://dc.example.com:389)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_start_tls',
            field=models.BooleanField(default=True, help_text='Use StartTLS for secure connection'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_user_search_base',
            field=models.CharField(blank=True, help_text='Base DN for user searches (e.g., OU=Users,DC=example,DC=com)', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ldap_user_search_filter',
            field=models.CharField(default='(sAMAccountName=%(user)s)', help_text='LDAP filter for user lookups', max_length=255),
        ),
    ]
