# Generated by Django 6.0.1 on 2026-01-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsetting_azure_ad_auto_create_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('website_monitoring', 'Website Monitoring Checks'), ('psa_sync', 'PSA Synchronization'), ('rmm_sync', 'RMM Synchronization'), ('password_breach_scan', 'Password Breach Scanning'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('domain_expiry_check', 'Domain Expiry Check')], max_length=50, unique=True),
        ),
    ]
