# Generated by Django 6.0.1 on 2026-01-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_update_check_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_api_token',
            field=models.CharField(blank=True, help_text='Snyk API token for vulnerability scanning', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_enabled',
            field=models.BooleanField(default=False, help_text='Enable Snyk security scanning'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_last_scan',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last Snyk scan', null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_org_id',
            field=models.CharField(blank=True, help_text='Snyk organization ID (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_scan_frequency',
            field=models.CharField(choices=[('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual Only')], default='daily', help_text='How often to run automatic scans', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_severity_threshold',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', help_text='Minimum severity level to report', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('website_monitoring', 'Website Monitoring Checks'), ('psa_sync', 'PSA Synchronization'), ('rmm_sync', 'RMM Synchronization'), ('password_breach_scan', 'Password Breach Scanning'), ('equipment_catalog_update', 'Equipment Catalog Update'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('domain_expiry_check', 'Domain Expiry Check'), ('update_check', 'System Update Check')], max_length=50, unique=True),
        ),
    ]
