# Generated by Django 6.0.1 on 2026-01-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_snykscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='snykscan',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='User requested cancellation'),
        ),
        migrations.AlterField(
            model_name='snykscan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timed Out')], default='pending', max_length=20),
        ),
    ]
