# Generated by Django 6.0.1 on 2026-01-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_vulnerability_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='github_pat',
            field=models.CharField(blank=True, help_text='GitHub Personal Access Token for bug reporting (encrypted)', max_length=500),
        ),
    ]
