# Generated by Django 6.0.1 on 2026-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_apply_gunicorn_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='global_kb_enabled',
            field=models.BooleanField(default=True, help_text='Enable Global Knowledge Base (Staff-only shared KB)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='monitoring_enabled',
            field=models.BooleanField(default=True, help_text='Enable Monitoring feature (Website & Service Monitoring)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='workflows_enabled',
            field=models.BooleanField(default=True, help_text='Enable Workflows & Automation feature'),
        ),
    ]
