# Generated by Django 6.0.1 on 2026-01-19 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_feature_toggles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_firewall_enabled', models.BooleanField(default=False, help_text='Enable IP-based firewall')),
                ('ip_firewall_mode', models.CharField(choices=[('allowlist', 'Allow List (block all except listed IPs)'), ('blocklist', 'Block List (allow all except listed IPs)')], default='blocklist', help_text='Firewall operation mode', max_length=20)),
                ('geoip_firewall_enabled', models.BooleanField(default=False, help_text='Enable GeoIP country-based firewall')),
                ('geoip_firewall_mode', models.CharField(choices=[('allowlist', 'Allow List (block all except listed countries)'), ('blocklist', 'Block List (allow all except listed countries)')], default='blocklist', help_text='GeoIP operation mode', max_length=20)),
                ('bypass_for_staff', models.BooleanField(default=True, help_text='Allow staff users to bypass firewall rules')),
                ('bypass_for_api', models.BooleanField(default=False, help_text='Allow API requests to bypass firewall rules')),
                ('log_blocked_requests', models.BooleanField(default=True, help_text='Log all blocked requests to audit log')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewall_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firewall Settings',
                'verbose_name_plural': 'Firewall Settings',
                'db_table': 'firewall_settings',
            },
        ),
        migrations.CreateModel(
            name='FirewallCountryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='2-letter ISO country code (e.g., US, GB, CN)', max_length=2)),
                ('country_name', models.CharField(help_text='Country name for display', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_country_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firewall_country_rules',
                'ordering': ['country_name'],
                'indexes': [models.Index(fields=['is_active', 'country_code'], name='firewall_co_is_acti_bda094_idx')],
                'unique_together': {('country_code',)},
            },
        ),
        migrations.CreateModel(
            name='FirewallIPRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP address or CIDR range (e.g., 192.168.1.100 or 192.168.0.0/16)', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Optional description (e.g., "Office Network", "VPN Gateway")', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firewall_ip_rules',
                'ordering': ['ip_address'],
                'indexes': [models.Index(fields=['is_active', 'ip_address'], name='firewall_ip_is_acti_2f9510_idx')],
            },
        ),
        migrations.CreateModel(
            name='FirewallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('block_reason', models.CharField(choices=[('ip_blocklist', 'IP in blocklist'), ('ip_not_in_allowlist', 'IP not in allowlist'), ('country_blocklist', 'Country in blocklist'), ('country_not_in_allowlist', 'Country not in allowlist'), ('geoip_lookup_failed', 'GeoIP lookup failed')], max_length=50)),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewall_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firewall_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='firewall_lo_timesta_1234f9_idx'), models.Index(fields=['ip_address', '-timestamp'], name='firewall_lo_ip_addr_ede97e_idx'), models.Index(fields=['country_code', '-timestamp'], name='firewall_lo_country_504018_idx')],
            },
        ),
    ]
