# Generated by Django 6.0.1 on 2026-01-30 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_securenote_access_token_securenote_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securenote',
            name='max_views',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of views before auto-expiring', null=True),
        ),
        migrations.CreateModel(
            name='SecureNoteAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('secure_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core.securenote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_note_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secure_note_access_logs',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['secure_note', '-accessed_at'], name='secure_note_secure__d8146c_idx'), models.Index(fields=['-accessed_at'], name='secure_note_accesse_9a4f49_idx')],
            },
        ),
    ]
