# Generated by Django 6.0.1 on 2026-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_systemsetting_stay_on_page_after_org_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='map_default_zoom',
            field=models.PositiveIntegerField(default=4, help_text='Default zoom level for dashboard maps (1-18)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='map_dragging_enabled',
            field=models.BooleanField(default=True, help_text='Enable map dragging by default (can be toggled per-map)'),
        ),
    ]
