# Generated by Django 6.0.1 on 2026-02-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_map_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='global_locations_map_enabled',
            field=models.BooleanField(default=True, help_text='Enable global locations map for superusers and staff'),
        ),
        migrations.AlterField(
            model_name='snykscan',
            name='project_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
