# Generated by Django 6.0.1 on 2026-02-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_migration_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='snykscan',
            name='scan_type',
            field=models.CharField(choices=[('open_source', 'Open Source (Dependencies)'), ('code', 'Code (SAST)'), ('container', 'Container (Docker)'), ('iac', 'Infrastructure as Code')], default='open_source', help_text='Type of Snyk product used for this scan', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_test_code',
            field=models.BooleanField(default=False, help_text='Scan source code with Snyk Code (snyk code test) - Requires Snyk Code enabled in dashboard'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_test_container',
            field=models.BooleanField(default=False, help_text='Scan Docker images with Snyk Container (snyk container test)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_test_iac',
            field=models.BooleanField(default=False, help_text='Scan IaC files with Snyk IaC (snyk iac test)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='snyk_test_open_source',
            field=models.BooleanField(default=True, help_text='Scan dependencies with Snyk Open Source (snyk test)'),
        ),
    ]
