# Generated by Django 6.0.1 on 2026-02-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('fully_managed', 'Fully Managed'), ('break_fix', 'Break/Fix'), ('co_managed', 'Co-Managed'), ('consulting', 'Consulting Only'), ('project_based', 'Project-Based'), ('internal', 'Internal / Staff'), ('other', 'Other')], default='', help_text='Client service type', max_length=50),
        ),
    ]
