# Generated by Django 5.0.14 on 2026-01-09 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.organization')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('server', 'Server'), ('workstation', 'Workstation'), ('laptop', 'Laptop'), ('network', 'Network Device'), ('printer', 'Printer'), ('phone', 'Phone'), ('mobile', 'Mobile Device'), ('other', 'Other')], default='other', max_length=50)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='core.tag')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assets', to='assets.contact')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveIntegerField()),
                ('relation_type', models.CharField(choices=[('related', 'Related To'), ('parent', 'Parent Of'), ('child', 'Child Of'), ('depends', 'Depends On'), ('documents', 'Documents')], default='related', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.organization')),
            ],
            options={
                'db_table': 'relationships',
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'last_name'], name='contacts_organiz_86b1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'name'], name='assets_organiz_c948ae_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asset_t_fc4c39_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['organization', 'source_type', 'source_id'], name='relationshi_organiz_9a572f_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['organization', 'target_type', 'target_id'], name='relationshi_organiz_10ec02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('source_type', 'source_id', 'target_type', 'target_id', 'relation_type')},
        ),
    ]
