# Generated by Django 6.0.1 on 2026-01-09 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Server, Workstation, Network Device', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('fa-server', 'Server'), ('fa-desktop', 'Desktop'), ('fa-laptop', 'Laptop'), ('fa-network-wired', 'Network'), ('fa-mobile-alt', 'Mobile'), ('fa-database', 'Database'), ('fa-cloud', 'Cloud'), ('fa-key', 'License'), ('fa-hdd', 'Storage'), ('fa-print', 'Printer'), ('fa-phone', 'Phone'), ('fa-car', 'Vehicle'), ('fa-building', 'Building'), ('fa-plug', 'Equipment'), ('fa-box', 'Generic')], default='fa-box', max_length=50)),
                ('color', models.CharField(default='#0d6efd', help_text='Hex color for UI display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('auto_number_prefix', models.CharField(blank=True, help_text='e.g., SRV-, WKS-', max_length=20)),
                ('auto_number_next', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='core.organization')),
            ],
            options={
                'db_table': 'asset_types',
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AssetTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Field label', max_length=100)),
                ('slug', models.SlugField(help_text='Internal field name', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'DateTime'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Phone'), ('ip_address', 'IP Address'), ('mac_address', 'MAC Address')], default='text', max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('show_in_list', models.BooleanField(default=True, help_text='Show in asset list view')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('dropdown_options', models.JSONField(blank=True, default=list, help_text='List of options for dropdown fields')),
                ('min_value', models.FloatField(blank=True, help_text='For number/decimal fields', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='For number/decimal fields', null=True)),
                ('regex_pattern', models.CharField(blank=True, help_text='Regex validation pattern', max_length=255)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='assets.assettype')),
            ],
            options={
                'db_table': 'asset_type_fields',
                'ordering': ['order', 'name'],
                'unique_together': {('asset_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FlexibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_number', models.CharField(blank=True, help_text='Auto-generated or manual', max_length=100)),
                ('field_values', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assettype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flexible_assets_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flexible_assets_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_assets', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='flexible_assets', to='core.tag')),
            ],
            options={
                'db_table': 'flexible_assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'asset_type'], name='flexible_as_organiz_1ada0a_idx'), models.Index(fields=['asset_number'], name='flexible_as_asset_n_1e037b_idx'), models.Index(fields=['name'], name='flexible_as_name_bb7b70_idx')],
            },
        ),
    ]
