# Generated by Django 6.0.1 on 2026-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_port_fields_to_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('av_receiver', 'AV Receiver'), ('access_control', 'Access Control System'), ('appliance', 'Appliance'), ('backup_appliance', 'Backup Appliance'), ('badge_printer', 'Badge Printer'), ('biometric_scanner', 'Biometric Scanner'), ('card_reader', 'Card Reader'), ('conference_phone', 'Conference Phone'), ('console_server', 'Console Server'), ('copier', 'Copier/MFP'), ('desktop', 'Desktop Computer'), ('digital_signage', 'Digital Signage'), ('dvr', 'Digital Video Recorder (DVR)'), ('display', 'Display/Monitor'), ('door_controller', 'Door Controller'), ('environmental_monitor', 'Environmental Monitor'), ('fiber_panel', 'Fiber Patch Panel'), ('firewall', 'Firewall'), ('gateway', 'Gateway'), ('generator', 'Generator'), ('hvac', 'HVAC System'), ('handheld', 'Handheld Scanner/Device'), ('phone', 'IP Phone'), ('iot_device', 'IoT Device'), ('kvm', 'KVM Switch'), ('label_printer', 'Label Printer'), ('laptop', 'Laptop'), ('lighting_control', 'Lighting Control'), ('load_balancer', 'Load Balancer'), ('mobile', 'Mobile Device'), ('modem', 'Modem'), ('nas', 'Network Attached Storage (NAS)'), ('bridge', 'Network Bridge'), ('switch', 'Network Switch'), ('nvr', 'Network Video Recorder (NVR)'), ('other', 'Other'), ('pbx', 'PBX System'), ('pda', 'PDA'), ('paging_system', 'Paging System'), ('patch_panel', 'Patch Panel'), ('plotter', 'Plotter'), ('pdu', 'Power Distribution Unit (PDU)'), ('printer', 'Printer'), ('projector', 'Projector'), ('router', 'Router'), ('scanner', 'Scanner'), ('security_camera', 'Security Camera'), ('sensor', 'Sensor'), ('server', 'Server'), ('rack', 'Server Rack/Cabinet'), ('thermostat', 'Smart Thermostat'), ('san', 'Storage Area Network (SAN)'), ('tablet', 'Tablet'), ('tape_drive', 'Tape Drive/Library'), ('terminal', 'Terminal'), ('thin_client', 'Thin Client'), ('ups', 'UPS (Uninterruptible Power Supply)'), ('video_conferencing', 'Video Conferencing System'), ('voip_gateway', 'VoIP Gateway'), ('wireless_ap', 'Wireless Access Point'), ('wireless_controller', 'Wireless Controller'), ('workstation', 'Workstation')], default='other', max_length=50),
        ),
    ]
