# Generated by Django 6.0.1 on 2026-01-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importjob_floor_plans_imported_and_more'),
        ('locations', '0005_alter_location_email_alter_location_floorplan_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='target_location',
            field=models.ForeignKey(blank=True, help_text='Optional: Link floor plans to existing location. Leave blank to create new location from MagicPlan data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='locations.location'),
        ),
    ]
