# Generated by Django 6.0.2 on 2026-02-18 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importjob_target_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, help_text='When this import was rolled back', null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, help_text='User who rolled back this import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs_rolled_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20),
        ),
    ]
