# Generated by Django 6.0.1 on 2026-01-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['title'], 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
    ]
