# Generated by Django 6.0.1 on 2026-01-19 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_add_rangermsp_provider'),
        ('processes', '0002_add_feature_toggles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='psa_ticket',
            field=models.ForeignKey(blank=True, help_text='Related PSA ticket for this execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_executions', to='integrations.psaticket'),
        ),
        migrations.CreateModel(
            name='ProcessExecutionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('execution_created', 'Execution Created'), ('execution_started', 'Execution Started'), ('execution_assigned', 'Execution Assigned'), ('execution_status_changed', 'Status Changed'), ('execution_completed', 'Execution Completed'), ('execution_failed', 'Execution Failed'), ('execution_cancelled', 'Execution Cancelled'), ('stage_completed', 'Stage Completed'), ('stage_uncompleted', 'Stage Uncompleted'), ('stage_notes_added', 'Stage Notes Added'), ('notes_updated', 'Execution Notes Updated'), ('due_date_changed', 'Due Date Changed')], max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('username', models.CharField(help_text='Username stored for history', max_length=150)),
                ('stage_title', models.CharField(blank=True, help_text='Stage title stored for history', max_length=255)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value (for updates)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value (for updates)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='processes.processexecution')),
                ('stage', models.ForeignKey(blank=True, help_text='Related stage (if action is stage-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='processes.processstage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_execution_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'process_execution_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution', '-created_at'], name='process_exe_executi_e014e1_idx'), models.Index(fields=['action_type', '-created_at'], name='process_exe_action__309558_idx'), models.Index(fields=['user', '-created_at'], name='process_exe_user_id_2fb521_idx')],
            },
        ),
    ]
