# Generated by Django 6.0.1 on 2026-01-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_processexecution_psa_ticket_processexecutionauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='psa_note_internal',
            field=models.BooleanField(default=False, help_text='Make PSA ticket note internal/private (not visible to customer)'),
        ),
    ]
