# Generated by Django 6.0.1 on 2026-01-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('core', '0005_scheduledtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_template', models.BooleanField(default=False, help_text='System templates cannot be deleted or modified by users')),
                ('vault_view', models.BooleanField(default=True, help_text='View passwords and secrets')),
                ('vault_create', models.BooleanField(default=False, help_text='Create passwords and secrets')),
                ('vault_edit', models.BooleanField(default=False, help_text='Edit passwords and secrets')),
                ('vault_delete', models.BooleanField(default=False, help_text='Delete passwords and secrets')),
                ('vault_export', models.BooleanField(default=False, help_text='Export passwords')),
                ('vault_view_password', models.BooleanField(default=True, help_text='View actual password values')),
                ('assets_view', models.BooleanField(default=True, help_text='View assets')),
                ('assets_create', models.BooleanField(default=False, help_text='Create assets')),
                ('assets_edit', models.BooleanField(default=False, help_text='Edit assets')),
                ('assets_delete', models.BooleanField(default=False, help_text='Delete assets')),
                ('docs_view', models.BooleanField(default=True, help_text='View documents')),
                ('docs_create', models.BooleanField(default=False, help_text='Create documents')),
                ('docs_edit', models.BooleanField(default=False, help_text='Edit documents')),
                ('docs_delete', models.BooleanField(default=False, help_text='Delete documents')),
                ('docs_publish', models.BooleanField(default=False, help_text='Publish/unpublish documents')),
                ('files_view', models.BooleanField(default=True, help_text='View files')),
                ('files_upload', models.BooleanField(default=False, help_text='Upload files')),
                ('files_delete', models.BooleanField(default=False, help_text='Delete files')),
                ('monitoring_view', models.BooleanField(default=True, help_text='View monitors')),
                ('monitoring_create', models.BooleanField(default=False, help_text='Create monitors')),
                ('monitoring_edit', models.BooleanField(default=False, help_text='Edit monitors')),
                ('monitoring_delete', models.BooleanField(default=False, help_text='Delete monitors')),
                ('monitoring_trigger', models.BooleanField(default=False, help_text='Manually trigger checks')),
                ('integrations_view', models.BooleanField(default=False, help_text='View integrations')),
                ('integrations_configure', models.BooleanField(default=False, help_text='Configure integrations')),
                ('integrations_sync', models.BooleanField(default=False, help_text='Trigger sync operations')),
                ('audit_view', models.BooleanField(default=False, help_text='View audit logs')),
                ('audit_export', models.BooleanField(default=False, help_text='Export audit logs')),
                ('org_view_members', models.BooleanField(default=True, help_text='View organization members')),
                ('org_invite_members', models.BooleanField(default=False, help_text='Invite new members')),
                ('org_manage_members', models.BooleanField(default=False, help_text='Edit/remove members')),
                ('org_manage_settings', models.BooleanField(default=False, help_text='Change organization settings')),
                ('api_access', models.BooleanField(default=False, help_text='Access API endpoints')),
                ('api_keys_manage', models.BooleanField(default=False, help_text='Create/manage API keys')),
                ('organization', models.ForeignKey(blank=True, help_text='If null, this is a system-wide template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='core.organization')),
            ],
            options={
                'db_table': 'role_templates',
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='role_template',
            field=models.ForeignKey(blank=True, help_text='Granular role template (overrides simple role if set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.roletemplate'),
        ),
    ]
