# Generated by Django 6.0.1 on 2026-01-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_roletemplate_membership_role_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='global_role_template',
            field=models.ForeignKey(blank=True, help_text='For staff users: role template that applies globally across all organizations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='accounts.roletemplate'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff User (MSP Tech)'), ('org_user', 'Organization User (Client)')], default='org_user', help_text='Staff users have global access across all organizations. Org users only see their assigned organizations.', max_length=20),
        ),
    ]
