# Generated by Django 6.0.1 on 2026-01-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_azure_fields_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('default', 'Default Blue'), ('dark', 'Dark Mode'), ('purple', 'Purple Haze'), ('green', 'Forest Green'), ('ocean', 'Ocean Blue'), ('sunset', 'Sunset Orange'), ('nord', 'Nord (Arctic)'), ('dracula', 'Dracula'), ('solarized', 'Solarized Light'), ('monokai', 'Monokai'), ('gruvbox', 'Gruvbox')], default='default', max_length=30),
        ),
    ]
