# Generated by Django 6.0.1 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_theme_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Custom background image for your profile', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_mode',
            field=models.CharField(choices=[('none', 'No Background Image'), ('custom', 'Custom Upload'), ('random', 'Random from Gallery')], default='none', max_length=20),
        ),
    ]
