# Generated by Django 6.0.1 on 2026-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_background_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_mode',
            field=models.CharField(choices=[('none', 'No Background Image'), ('custom', 'Custom Upload'), ('random', 'Random from Internet')], default='none', max_length=20),
        ),
    ]
