# Generated by Django 5.0.14 on 2026-01-09 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(choices=[('html', 'HTML (WYSIWYG)'), ('markdown', 'Markdown')], default='html', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Is this a reusable template?'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='content_type',
            field=models.CharField(default='markdown', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='folder', help_text='Font Awesome icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='docs.documentcategory')),
            ],
            options={
                'verbose_name_plural': 'Document categories',
                'db_table': 'document_categories',
                'ordering': ['order', 'name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docs.documentcategory'),
        ),
        migrations.CreateModel(
            name='DocumentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')], default='yellow', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='docs.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_flags',
                'unique_together': {('user', 'document')},
            },
        ),
    ]
