# Generated by Django 6.0.1 on 2026-01-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_content_type_document_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Global KB - visible to all organizations'),
        ),
    ]
