# Generated by Django 6.0.1 on 2026-01-10 18:15
#
# NOTE: This migration was converted to a no-op because it caused issues
# when querying models before all schema changes were applied.
# Template seeding is now handled by the installer script which runs
# management commands AFTER all migrations complete.

from django.db import migrations


def noop(apps, schema_editor):
    """No-op - template seeding handled by installer"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_add_diagram_thumbnail'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
