# Generated by Django 6.0.1 on 2026-01-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_seed_initial_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for template (300x200)', null=True, upload_to='documents/previews/'),
        ),
    ]
