# Generated by Django 6.0.1 on 2026-01-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_scan_cancellation'),
        ('docs', '0009_make_diagram_organization_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization for org-specific categories. NULL for global KB categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='core.organization'),
        ),
    ]
