# Generated by Django 5.0.14 on 2026-01-09 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSAConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('connectwise_manage', 'ConnectWise Manage'), ('autotask', 'Autotask PSA'), ('halo_psa', 'HaloPSA'), ('kaseya_bms', 'Kaseya BMS'), ('syncro', 'Syncro'), ('freshservice', 'Freshservice'), ('zendesk', 'Zendesk')], max_length=50)),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('encrypted_credentials', models.TextField(help_text='Encrypted JSON with API keys, secrets, tokens')),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_companies', models.BooleanField(default=True)),
                ('sync_contacts', models.BooleanField(default=True)),
                ('sync_tickets', models.BooleanField(default=True)),
                ('sync_agreements', models.BooleanField(default=False)),
                ('sync_projects', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='Custom field mappings')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_connections', to='core.organization')),
            ],
            options={
                'db_table': 'psa_connections',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PSACompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_companies', to='core.organization')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='integrations.psaconnection')),
            ],
            options={
                'db_table': 'psa_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalObjectMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('external_type', models.CharField(max_length=50)),
                ('external_hash', models.CharField(blank=True, max_length=64)),
                ('local_type', models.CharField(max_length=50)),
                ('local_id', models.PositiveIntegerField()),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_object_maps', to='core.organization')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_maps', to='integrations.psaconnection')),
            ],
            options={
                'db_table': 'external_object_maps',
            },
        ),
        migrations.CreateModel(
            name='PSAContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='integrations.psacompany')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='integrations.psaconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_contacts', to='core.organization')),
            ],
            options={
                'db_table': 'psa_contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PSATicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('ticket_number', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=50)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='integrations.psacompany')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='integrations.psaconnection')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='integrations.psacontact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_tickets', to='core.organization')),
            ],
            options={
                'db_table': 'psa_tickets',
                'ordering': ['-external_updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='psacompany',
            index=models.Index(fields=['organization', 'name'], name='psa_compani_organiz_3aacaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='psacompany',
            unique_together={('connection', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='externalobjectmap',
            index=models.Index(fields=['organization', 'external_type', 'external_id'], name='external_ob_organiz_c2443f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalobjectmap',
            index=models.Index(fields=['local_type', 'local_id'], name='external_ob_local_t_ab6520_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalobjectmap',
            unique_together={('connection', 'external_type', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='psacontact',
            index=models.Index(fields=['organization', 'last_name'], name='psa_contact_organiz_941c66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='psacontact',
            unique_together={('connection', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='psaticket',
            index=models.Index(fields=['organization', 'status'], name='psa_tickets_organiz_ee48ac_idx'),
        ),
        migrations.AddIndex(
            model_name='psaticket',
            index=models.Index(fields=['external_updated_at'], name='psa_tickets_externa_c310e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='psaticket',
            unique_together={('connection', 'external_id')},
        ),
    ]
