# Generated by Django 6.0.1 on 2026-01-11 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_rackmount_fields'),
        ('core', '0006_systemsetting_azure_ad_auto_create_users_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMMConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('ninjaone', 'NinjaOne'), ('datto_rmm', 'Datto RMM'), ('connectwise_automate', 'ConnectWise Automate'), ('atera', 'Atera')], max_length=50)),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('encrypted_credentials', models.TextField(help_text='Encrypted JSON with API keys, secrets, tokens')),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_devices', models.BooleanField(default=True)),
                ('sync_alerts', models.BooleanField(default=True)),
                ('sync_software', models.BooleanField(default=False)),
                ('sync_network_config', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('map_to_assets', models.BooleanField(default=True, help_text='Automatically map RMM devices to Assets')),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='Custom field mappings')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_connections', to='core.organization')),
            ],
            options={
                'db_table': 'rmm_connections',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RMMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('workstation', 'Workstation'), ('server', 'Server'), ('laptop', 'Laptop'), ('network', 'Network Device'), ('mobile', 'Mobile Device'), ('virtual', 'Virtual Machine'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('os_type', models.CharField(blank=True, choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS'), ('ios', 'iOS'), ('android', 'Android'), ('other', 'Other')], max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='integrations.rmmconnection')),
                ('linked_asset', models.ForeignKey(blank=True, help_text='Associated Asset if mapped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmm_devices', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_devices', to='core.organization')),
            ],
            options={
                'db_table': 'rmm_devices',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='RMMAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('alert_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=50)),
                ('triggered_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_alerts', to='core.organization')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='integrations.rmmconnection')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='integrations.rmmdevice')),
            ],
            options={
                'db_table': 'rmm_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='RMMSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_inventory', to='integrations.rmmconnection')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='integrations.rmmdevice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_software', to='core.organization')),
            ],
            options={
                'db_table': 'rmm_software',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.AddIndex(
            model_name='rmmdevice',
            index=models.Index(fields=['organization', 'device_name'], name='rmm_devices_organiz_a2e34c_idx'),
        ),
        migrations.AddIndex(
            model_name='rmmdevice',
            index=models.Index(fields=['is_online'], name='rmm_devices_is_onli_6e0f71_idx'),
        ),
        migrations.AddIndex(
            model_name='rmmdevice',
            index=models.Index(fields=['last_seen'], name='rmm_devices_last_se_8aec62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rmmdevice',
            unique_together={('connection', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='rmmalert',
            index=models.Index(fields=['organization', 'status'], name='rmm_alerts_organiz_57e440_idx'),
        ),
        migrations.AddIndex(
            model_name='rmmalert',
            index=models.Index(fields=['severity', 'status'], name='rmm_alerts_severit_168637_idx'),
        ),
        migrations.AddIndex(
            model_name='rmmalert',
            index=models.Index(fields=['triggered_at'], name='rmm_alerts_trigger_4ae610_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rmmalert',
            unique_together={('connection', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='rmmsoftware',
            index=models.Index(fields=['organization', 'name'], name='rmm_softwar_organiz_10d242_idx'),
        ),
        migrations.AddIndex(
            model_name='rmmsoftware',
            index=models.Index(fields=['device', 'name'], name='rmm_softwar_device__329781_idx'),
        ),
    ]
