# Generated by Django 6.0.1 on 2026-01-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_add_org_import_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psaconnection',
            name='provider_type',
            field=models.CharField(choices=[('connectwise_manage', 'ConnectWise Manage'), ('autotask', 'Autotask PSA'), ('halo_psa', 'HaloPSA'), ('kaseya_bms', 'Kaseya BMS'), ('syncro', 'Syncro'), ('freshservice', 'Freshservice'), ('zendesk', 'Zendesk'), ('itflow', 'ITFlow'), ('rangermsp', 'RangerMSP (CommitCRM)')], max_length=50),
        ),
    ]
