# Generated by Django 6.0.1 on 2026-01-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Building, room, row', max_length=255)),
                ('units', models.PositiveIntegerField(default=42, help_text='Rack units (U)')),
                ('width_inches', models.PositiveIntegerField(default=19)),
                ('depth_inches', models.PositiveIntegerField(blank=True, null=True)),
                ('power_capacity_watts', models.PositiveIntegerField(blank=True, null=True)),
                ('power_allocated_watts', models.PositiveIntegerField(default=0)),
                ('cooling_capacity_btu', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='core.organization')),
            ],
            options={
                'db_table': 'racks',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RackDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_unit', models.PositiveIntegerField(help_text='Starting U position (1 = bottom)')),
                ('units', models.PositiveIntegerField(default=1, help_text='Height in U')),
                ('power_draw_watts', models.PositiveIntegerField(blank=True, null=True)),
                ('asset_id', models.PositiveIntegerField(blank=True, help_text='Link to Asset', null=True)),
                ('color', models.CharField(default='#0d6efd', help_text='Hex color for visualization', max_length=7)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_devices', to='monitoring.rack')),
            ],
            options={
                'db_table': 'rack_devices',
                'ordering': ['rack', 'start_unit'],
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(help_text='e.g., 192.168.1.0/24', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('vlan_name', models.CharField(blank=True, max_length=100)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_servers', models.JSONField(default=list, help_text='List of DNS server IPs')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='core.organization')),
            ],
            options={
                'db_table': 'subnets',
                'ordering': ['network'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('dhcp', 'DHCP Pool')], default='available', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address in XX:XX:XX:XX:XX:XX format', max_length=17)),
                ('description', models.TextField(blank=True)),
                ('asset_id', models.PositiveIntegerField(blank=True, help_text='Link to Asset', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='monitoring.subnet')),
            ],
            options={
                'db_table': 'ip_addresses',
                'ordering': ['subnet', 'ip_address'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('check_interval_minutes', models.PositiveIntegerField(default=60, help_text='How often to check')),
                ('is_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('last_response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_issuer', models.CharField(blank=True, max_length=255)),
                ('ssl_warning_days', models.PositiveIntegerField(default=30, help_text='Warn X days before expiration')),
                ('domain_expires_at', models.DateTimeField(blank=True, null=True)),
                ('domain_registrar', models.CharField(blank=True, max_length=255)),
                ('domain_warning_days', models.PositiveIntegerField(default=60, help_text='Warn X days before expiration')),
                ('notify_on_down', models.BooleanField(default=True)),
                ('notify_on_ssl_expiry', models.BooleanField(default=True)),
                ('notify_on_domain_expiry', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_monitors', to='core.organization')),
            ],
            options={
                'db_table': 'website_monitors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('expiration_type', models.CharField(choices=[('ssl_cert', 'SSL Certificate'), ('domain', 'Domain Registration'), ('license', 'Software License'), ('contract', 'Contract/Agreement'), ('warranty', 'Warranty'), ('insurance', 'Insurance'), ('certification', 'Certification'), ('other', 'Other')], max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('warning_days', models.PositiveIntegerField(default=30)),
                ('related_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expirations', to='core.organization')),
            ],
            options={
                'db_table': 'expirations',
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['organization', 'expires_at'], name='expirations_organiz_3d523f_idx'), models.Index(fields=['expiration_type'], name='expirations_expirat_d45b61_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['organization', 'location'], name='racks_organiz_8c4963_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rackdevice',
            unique_together={('rack', 'start_unit')},
        ),
        migrations.AddIndex(
            model_name='subnet',
            index=models.Index(fields=['organization', 'network'], name='subnets_organiz_714adc_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['subnet', 'status'], name='ip_addresse_subnet__c9bdb1_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address'], name='ip_addresse_ip_addr_436d55_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['mac_address'], name='ip_addresse_mac_add_b2befa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('subnet', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='websitemonitor',
            index=models.Index(fields=['organization', 'is_enabled'], name='website_mon_organiz_3d08f5_idx'),
        ),
        migrations.AddIndex(
            model_name='websitemonitor',
            index=models.Index(fields=['ssl_expires_at'], name='website_mon_ssl_exp_d0dafe_idx'),
        ),
        migrations.AddIndex(
            model_name='websitemonitor',
            index=models.Index(fields=['domain_expires_at'], name='website_mon_domain__624dff_idx'),
        ),
    ]
