# Generated by Django 6.0.1 on 2026-01-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackdevice',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='rack',
            name='aisle',
            field=models.CharField(blank=True, help_text='Aisle/row identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='rack',
            name='datacenter',
            field=models.CharField(blank=True, help_text='Datacenter/facility name', max_length=100),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='photo',
            field=models.ImageField(blank=True, help_text='Device photo', null=True, upload_to='rack_devices/'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='location',
            field=models.CharField(blank=True, help_text='Additional location details', max_length=255),
        ),
        migrations.AlterField(
            model_name='rack',
            name='width_inches',
            field=models.PositiveIntegerField(choices=[(19, '19"'), (23, '23"')], default=19),
        ),
    ]
