# Generated by Django 6.0.1 on 2026-01-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_rackdevice_photo_url_rack_aisle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemonitor',
            name='ssl_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitemonitor',
            name='ssl_serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='websitemonitor',
            name='ssl_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='websitemonitor',
            name='ssl_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
