# Generated by Django 5.0.14 on 2026-01-09 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('encrypted_password', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='passwords', to='core.tag')),
            ],
            options={
                'db_table': 'passwords',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PasswordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('asset', 'Asset'), ('document', 'Document'), ('contact', 'Contact'), ('integration', 'Integration')], max_length=50)),
                ('relation_id', models.PositiveIntegerField()),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='vault.password')),
            ],
            options={
                'db_table': 'password_relations',
            },
        ),
        migrations.AddIndex(
            model_name='password',
            index=models.Index(fields=['organization', 'title'], name='passwords_organiz_93236e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordrelation',
            index=models.Index(fields=['relation_type', 'relation_id'], name='password_re_relatio_659ff3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='passwordrelation',
            unique_together={('password', 'relation_type', 'relation_id')},
        ),
    ]
