# Generated by Django 5.0.14 on 2026-01-09 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Password expiration date', null=True),
        ),
        migrations.AddField(
            model_name='password',
            name='expiry_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='password',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Personal password (My Vault)'),
        ),
        migrations.AddField(
            model_name='password',
            name='otp_issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='password',
            name='otp_secret',
            field=models.TextField(blank=True, help_text='Encrypted TOTP secret'),
        ),
        migrations.AddField(
            model_name='password',
            name='password_type',
            field=models.CharField(choices=[('password', 'Password'), ('otp', 'OTP/TOTP'), ('api_key', 'API Key'), ('ssh_key', 'SSH Key')], default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='password',
            name='personal_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
