# Generated by Django 6.0.1 on 2026-01-09 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_password_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('encrypted_content', models.TextField()),
                ('category', models.CharField(blank=True, help_text='Optional: Organize, Notes, Snippets, etc.', max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_vault',
                'ordering': ['-is_favorite', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'title'], name='personal_va_user_id_7f83c2_idx'), models.Index(fields=['user', 'is_favorite'], name='personal_va_user_id_dffeb4_idx')],
            },
        ),
    ]
