# Generated by Django 6.0.1 on 2026-01-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsetting'),
        ('vault', '0003_personalvault'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for folder icon', max_length=7)),
                ('icon', models.CharField(default='fa-folder', help_text='FontAwesome icon class', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_folders', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='vault.passwordfolder')),
            ],
            options={
                'db_table': 'password_folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='password',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Password folder for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords', to='vault.passwordfolder'),
        ),
        migrations.AddIndex(
            model_name='passwordfolder',
            index=models.Index(fields=['organization', 'parent'], name='password_fo_organiz_6a502c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='passwordfolder',
            unique_together={('organization', 'name', 'parent')},
        ),
    ]
