# Generated by Django 6.0.1 on 2026-01-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_passwordfolder_password_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='database_host',
            field=models.CharField(blank=True, help_text='Database hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='password',
            name='database_name',
            field=models.CharField(blank=True, help_text='Database name', max_length=255),
        ),
        migrations.AddField(
            model_name='password',
            name='database_port',
            field=models.CharField(blank=True, help_text='Database port', max_length=10),
        ),
        migrations.AddField(
            model_name='password',
            name='database_type',
            field=models.CharField(blank=True, help_text='Database type (MySQL, PostgreSQL, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='password',
            name='domain',
            field=models.CharField(blank=True, help_text='Domain name for Windows/AD', max_length=255),
        ),
        migrations.AddField(
            model_name='password',
            name='email_port',
            field=models.CharField(blank=True, help_text='Email port', max_length=10),
        ),
        migrations.AddField(
            model_name='password',
            name='email_server',
            field=models.CharField(blank=True, help_text='Email server (IMAP/SMTP)', max_length=255),
        ),
        migrations.AddField(
            model_name='password',
            name='license_key',
            field=models.TextField(blank=True, help_text='Software license key'),
        ),
        migrations.AddField(
            model_name='password',
            name='ssh_host',
            field=models.CharField(blank=True, help_text='SSH hostname/IP', max_length=255),
        ),
        migrations.AddField(
            model_name='password',
            name='ssh_port',
            field=models.CharField(blank=True, default='22', help_text='SSH port', max_length=10),
        ),
        migrations.AlterField(
            model_name='password',
            name='password_type',
            field=models.CharField(choices=[('website', 'Website Login'), ('email', 'Email Account'), ('windows_ad', 'Windows/Active Directory'), ('database', 'Database'), ('ssh_key', 'SSH Key'), ('api_key', 'API Key'), ('otp', 'OTP/TOTP (2FA)'), ('credit_card', 'Credit Card'), ('network_device', 'Network Device'), ('server', 'Server/VPS'), ('ftp', 'FTP/SFTP'), ('vpn', 'VPN'), ('wifi', 'WiFi Network'), ('software_license', 'Software License'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
