# Generated by Django 6.0.1 on 2026-01-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_scheduledtask_task_type'),
        ('docs', '0009_make_diagram_organization_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Location name (e.g., 'Main Office', 'Warehouse #2')", max_length=255)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('warehouse', 'Warehouse'), ('datacenter', 'Data Center'), ('retail', 'Retail Store'), ('branch', 'Branch Office'), ('manufacturing', 'Manufacturing'), ('coworking', 'Co-working Space'), ('remote', 'Remote Site'), ('other', 'Other')], default='office', max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude coordinate', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude coordinate', max_digits=10, null=True)),
                ('building_sqft', models.IntegerField(blank=True, help_text='Total building square footage', null=True)),
                ('floors_count', models.IntegerField(blank=True, help_text='Number of floors in building', null=True)),
                ('year_built', models.IntegerField(blank=True, help_text='Year building was constructed', null=True)),
                ('property_type', models.CharField(blank=True, help_text="Property classification (e.g., 'Commercial Office')", max_length=100)),
                ('property_id', models.CharField(blank=True, help_text='Tax assessor parcel ID', max_length=100)),
                ('google_place_id', models.CharField(blank=True, help_text='Google Places API identifier', max_length=255)),
                ('external_data', models.JSONField(blank=True, default=dict, help_text='Raw data from external APIs (property records, etc.)')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/headquarters location for organization')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned'), ('closed', 'Closed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('satellite_image', models.ImageField(blank=True, help_text='Satellite imagery of building', upload_to='locations/satellite/%Y/%m/')),
                ('street_view_image', models.ImageField(blank=True, help_text='Street view photo of building', upload_to='locations/street/%Y/%m/')),
                ('area_map_image', models.ImageField(blank=True, help_text='Area map showing surrounding context', upload_to='locations/maps/%Y/%m/')),
                ('floorplan_generated', models.BooleanField(default=False, help_text='Has floor plan been auto-generated?')),
                ('floorplan_generated_at', models.DateTimeField(blank=True, help_text='When floor plan was last generated', null=True)),
                ('floorplan_generation_status', models.CharField(blank=True, help_text='Status of floor plan generation (pending, processing, completed, failed)', max_length=50)),
                ('floorplan_error', models.TextField(blank=True, help_text='Error message if floor plan generation failed')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.organization')),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_number', models.IntegerField(default=1, help_text='Floor level (1 = ground floor, 0 = basement, 2 = second floor)')),
                ('floor_name', models.CharField(help_text="Descriptive name (e.g., 'Ground Floor', '2nd Floor', 'Basement')", max_length=100)),
                ('width_feet', models.DecimalField(decimal_places=2, help_text='Floor width in feet', max_digits=8)),
                ('length_feet', models.DecimalField(decimal_places=2, help_text='Floor length in feet', max_digits=8)),
                ('ceiling_height_feet', models.DecimalField(blank=True, decimal_places=2, help_text='Ceiling height in feet', max_digits=5, null=True)),
                ('total_sqft', models.IntegerField(help_text='Total floor area in square feet')),
                ('source', models.CharField(choices=[('tax_record', 'Tax/Property Record'), ('satellite', 'Satellite Imagery Analysis'), ('building_footprint', 'Building Footprint Data'), ('user_input', 'User Provided'), ('ai_estimate', 'AI Estimation'), ('hybrid', 'Multiple Sources')], default='ai_estimate', help_text='Primary data source for dimensions', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0.00 to 1.00)', max_digits=4, null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='Detailed AI analysis results and source data')),
                ('diagram_xml', models.TextField(blank=True, help_text='Draw.io XML for floor plan')),
                ('template_used', models.CharField(blank=True, help_text='Template used for generation (office, warehouse, etc.)', max_length=100)),
                ('include_network', models.BooleanField(default=True, help_text='Include network equipment (APs, switches, cameras)')),
                ('include_furniture', models.BooleanField(default=True, help_text='Include furniture and equipment')),
                ('diagram', models.ForeignKey(blank=True, help_text='Link to generated diagram in docs module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_locations', to='docs.diagram')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='locations.location')),
            ],
            options={
                'db_table': 'location_floor_plans',
                'ordering': ['location', 'floor_number'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'is_primary'], name='locations_organiz_c1b119_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'status'], name='locations_organiz_909dce_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_latitud_4052bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='locationfloorplan',
            index=models.Index(fields=['location', 'floor_number'], name='location_fl_locatio_4d9782_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationfloorplan',
            unique_together={('location', 'floor_number')},
        ),
    ]
