# Generated by Django 6.0.1 on 2026-01-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_city_organization_country_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='location',
            name='associated_organizations',
            field=models.ManyToManyField(blank=True, help_text='Organizations that have access to this shared location', related_name='associated_locations', to='core.organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Shared location (e.g., data center, co-location facility) that multiple organizations can use'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Owner organization (leave blank for shared/global locations)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_shared'], name='locations_is_shar_ec2e5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'name'), name='unique_org_location_name'),
        ),
    ]
