# Generated by Django 6.0.1 on 2026-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_locationfloorplan_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='floorplan_error',
            field=models.TextField(blank=True, default='', help_text='Error message if floor plan generation failed'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floorplan_generation_status',
            field=models.CharField(blank=True, default='', help_text='Status of floor plan generation (pending, processing, completed, failed)', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(blank=True, default='', help_text='Google Places API identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='property_id',
            field=models.CharField(blank=True, default='', help_text='Tax assessor parcel ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='property_type',
            field=models.CharField(blank=True, default='', help_text="Property classification (e.g., 'Commercial Office')", max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_address_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='locationfloorplan',
            name='diagram_xml',
            field=models.TextField(blank=True, default='', help_text='Draw.io XML for floor plan'),
        ),
        migrations.AlterField(
            model_name='locationfloorplan',
            name='template_used',
            field=models.CharField(blank=True, default='', help_text='Template used for generation (office, warehouse, etc.)', max_length=100),
        ),
    ]
