# Generated by Django 6.0.1 on 2026-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_email_alter_location_floorplan_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='property_diagram',
            field=models.ImageField(blank=True, help_text='Property diagram/floor plan from tax collector or property appraiser records', upload_to='locations/diagrams/%Y/%m/'),
        ),
    ]
