# Generated by Django 6.0.1 on 2026-02-08 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_global_locations_map_enabled'),
        ('locations', '0007_alter_location_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Friendly name for this WAN connection (e.g., 'Primary Internet', 'Backup MPLS')", max_length=255)),
                ('wan_type', models.CharField(choices=[('internet', 'Internet'), ('mpls', 'MPLS'), ('vpn', 'VPN'), ('dedicated', 'Dedicated Circuit'), ('fiber', 'Fiber'), ('cable', 'Cable'), ('dsl', 'DSL'), ('satellite', 'Satellite'), ('wireless', 'Wireless'), ('other', 'Other')], default='internet', max_length=20)),
                ('circuit_id', models.CharField(blank=True, help_text='ISP circuit ID or account number', max_length=255)),
                ('isp_name', models.CharField(help_text='Internet Service Provider or carrier name', max_length=255)),
                ('isp_account_number', models.CharField(blank=True, help_text='Account number with ISP', max_length=255)),
                ('isp_support_phone', models.CharField(blank=True, help_text='ISP support phone number', max_length=50)),
                ('isp_support_email', models.EmailField(blank=True, help_text='ISP support email', max_length=254)),
                ('bandwidth_download_mbps', models.DecimalField(blank=True, decimal_places=2, help_text='Download bandwidth in Mbps', max_digits=10, null=True)),
                ('bandwidth_upload_mbps', models.DecimalField(blank=True, decimal_places=2, help_text='Upload bandwidth in Mbps', max_digits=10, null=True)),
                ('static_ip', models.GenericIPAddressField(blank=True, help_text='Static IP address (if applicable)', null=True)),
                ('subnet_mask', models.GenericIPAddressField(blank=True, help_text='Subnet mask', null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, help_text='Default gateway', null=True)),
                ('dns_primary', models.GenericIPAddressField(blank=True, help_text='Primary DNS server', null=True)),
                ('dns_secondary', models.GenericIPAddressField(blank=True, help_text='Secondary DNS server', null=True)),
                ('monitoring_enabled', models.BooleanField(default=False, help_text='Enable uptime and performance monitoring for this WAN connection')),
                ('monitor_target', models.CharField(blank=True, help_text='IP address or hostname to ping/monitor for this WAN (e.g., gateway IP or public IP)', max_length=255)),
                ('monitor_interval_minutes', models.PositiveIntegerField(default=5, help_text='How often to check WAN status (in minutes)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned'), ('down', 'Down'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time this WAN was checked', null=True)),
                ('last_response_time_ms', models.PositiveIntegerField(blank=True, help_text='Last ping response time in milliseconds', null=True)),
                ('uptime_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Uptime percentage (last 30 days)', max_digits=5, null=True)),
                ('last_down_at', models.DateTimeField(blank=True, help_text='Last time this WAN went down', null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly cost in dollars', max_digits=10, null=True)),
                ('contract_start_date', models.DateField(blank=True, help_text='Contract start date', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='Contract end date', null=True)),
                ('contract_term_months', models.PositiveIntegerField(blank=True, help_text='Contract term length in months', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this WAN connection')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary WAN connection for this location')),
                ('location', models.ForeignKey(help_text='Location where this WAN connection is terminated', on_delete=django.db.models.deletion.CASCADE, related_name='wan_connections', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wan_connections', to='core.organization')),
            ],
            options={
                'verbose_name': 'WAN Connection',
                'verbose_name_plural': 'WAN Connections',
                'db_table': 'wan_connections',
                'ordering': ['location', '-is_primary', 'name'],
                'indexes': [models.Index(fields=['organization', 'status'], name='wan_connect_organiz_0dc9be_idx'), models.Index(fields=['location', 'is_primary'], name='wan_connect_locatio_ea2634_idx'), models.Index(fields=['monitoring_enabled'], name='wan_connect_monitor_8e233b_idx')],
            },
        ),
    ]
